//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saityno_back_end
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class saitynasEntities2 : DbContext
    {
        public saitynasEntities2()
            : base("name=saitynasEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<continent> continents { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<rating> ratings { get; set; }
    }
}
