//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saityno_back_end
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public string username { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string country { get; set; }
        public int age { get; set; }
        public string fk_team { get; set; }
    }
}
