//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saityno_back_end
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int id { get; set; }
        public int times_rated { get; set; }
        public int total { get; set; }
    }
}
